<a href="https://colab.research.google.com/github/Hrish52/Tokyo-Olympics-2021-Analytics/blob/main/Tokyo_Olympics_2021_Medal_Efficiency_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tokyo Olympics 2021 - Medal Efficiency Project

### Description


This project delves into the true performance of nations at the Tokyo Olympics 2021 by evaluating their medal efficiency. Beyond raw medal counts, we analyze how effectively each country converted its resources into Olympic success.

By comparing medal hauls against factors like the number of participating athletes, population, and GDP per capita, this project highlights countries that truly "punch above their weight" on the global sporting stage. Key metrics explored include:

*   **Medals per Athlete**: To understand the productivity of each athlete in a country's delegation.
*   **Medals per Capita**: To gauge a nation's sporting prowess relative to its population size.
*   **Medals per $B GDP**: To assess efficiency in medal acquisition concerning economic power.

This analysis provides a nuanced perspective on Olympic success, revealing the nations with exceptional athletic programs and resource utilization.

### Phase 1: Data Loading & Exploration

The goal of this phase is to load the Tokyo Olympics 2021 datasets and develop a thorough understanding of their structure before any cleaning or transformation.

This includes inspecting column names, data types, missing values, and duplicates across all five tables (Athletes, Coaches,
EntriesGender, Medals, Teams).

We also examine how the tables relate to
each other — identifying join keys, spotting country name mismatches, and understanding what each row represents. These observations will directly guide the cleaning and merging decisions in Phase 2.

Dataset source: https://github.com/Hrish52/Tokyo-Olympics-2021-Analytics/tree/main/Data

Files: Athletes.xlsx, Coaches.xlsx, EntriesGender.xlsx, Medals.xlsx, Teams.xlsx

#### STEP 1: Load all datasets

TODO: Update these paths to wherever you saved the CSV/Excel files

In [1]:
import pandas as pd

base_url = 'https://raw.githubusercontent.com/Hrish52/Tokyo-Olympics-2021-Analytics/main/Data/'
files = {
    'Athletes': 'Athletes.csv',
    'Coaches': 'Coaches.csv',
    'EntriesGender': 'EntriesGender.csv',
    'Medals': 'Medals.csv',
    'Teams': 'Teams.csv'
}

dfs = {}
for name, filename in files.items():
    file_url = base_url + filename
    dfs[name] = pd.read_csv(file_url)
    print(f'Loaded {name} DataFrame.')

Loaded Athletes DataFrame.
Loaded Coaches DataFrame.
Loaded EntriesGender DataFrame.
Loaded Medals DataFrame.
Loaded Teams DataFrame.

#### STEP 2: Quick overview of each dataset

TODO: For each dataframe, print:
- .shape        → how many rows and columns?
- .columns      → what are the column names?
- .dtypes       → what types is pandas inferring?
- .head()       → does the data look right?

In [2]:
for name, df in dfs.items():
    print(f"\n=== {name} ===")
    print(f"Shape: {df.shape}")
    print(f"Columns: {df.columns.tolist()}")
    print(f"Data Types:\n{df.dtypes}")
    print(f"Head:\n")
    display(df.head())

=== Athletes ===
Shape: (11085, 3)
Columns: ['Name', 'NOC', 'Discipline']
Data Types:
Name          object
NOC           object
Discipline    object
dtype: object
Head:

                Name     NOC           Discipline
0    AALERUD Katrine  Norway         Cycling Road
1        ABAD Nestor   Spain  Artistic Gymnastics
2  ABAGNALE Giovanni   Italy               Rowing
3     ABALDE Alberto   Spain           Basketball
4      ABALDE Tamara   Spain           Basketball

=== Coaches ===
Shape: (394, 4)
Columns: ['Name', 'NOC', 'Discipline', 'Event']
Data Types:
Name          object
NOC           object
Discipline    object
Event         object
dtype: object
Head:

              Name            NOC  Discipline Event
0  ABDELMAGID Wael          Egypt    Football   NaN
1        ABE Junya          Japan  Volleyball   NaN
2    ABE Katsuhiko          Japan  Basketball   NaN
3     ADAMA Cherif  Côte d'Ivoire    Football   NaN
4       AGEBA Yuya          Japan  Volleyball   NaN

=== EntriesGender ===
Shape: (46, 4)
Columns: ['Discipline', 'Female', 'Male', 'Total']
Data Types:
Discipline    object
Female         int64
Male           int64
Total          int64
dtype: object
Head:

            Discipline  Female  Male  Total
0       3x3 Basketball      32    32     64
1              Archery      64    64    128
2  Artistic Gymnastics      98    98    196
3    Artistic Swimming     105     0    105
4            Athletics     969  1072   2041

=== Medals ===
Shape: (93, 7)
Columns: ['Rank', 'Team/NOC', 'Gold', 'Silver', 'Bronze', 'Total', 'Rank by Total']
Data Types:
Rank              int64
Team/NOC         object
Gold              int64
Silver            int64
Bronze            int64
Total             int64
Rank by Total     int64
dtype: object
Head:

,Rank,Team/NOC,Gold,Silver,Bronze,Total,Rank by Total
0,1,United States of America,39,41,33,113,1
1,2,People's Republic of China,38,32,18,88,2
2,3,Japan,27,14,17,58,5
3,4,Great Britain,22,21,22,65,4
4,5,ROC,20,28,23,71,3

=== Teams ===
Shape: (743, 4)
Columns: ['Name', 'Discipline', 'NOC', 'Event']
Data Types:
Name          object
Discipline    object
NOC           object
Event         object
dtype: object
Head:

      Name      Discipline                         NOC  Event
0  Belgium  3x3 Basketball                     Belgium    Men
1    China  3x3 Basketball  People's Republic of China    Men
2    China  3x3 Basketball  People's Republic of China  Women
3   France  3x3 Basketball                      France  Women
4    Italy  3x3 Basketball                       Italy  Women

#### STEP 3: Check for data quality issues

TODO: For each dataframe, check:
- .isnull().sum()       → any missing values?
- .duplicated().sum()   → any duplicate rows?

In [3]:
for name, df in dfs.items():
    print(f"\n=== {name} Data Quality Check ===")
    print("Missing values:\n")
    display(df.isnull().sum())

    print("\nDuplicate rows:")
    num_duplicates = df.duplicated().sum()
    print(num_duplicates)
    if num_duplicates > 0:
        print(f"First 5 duplicated rows in {name}:\n")
        display(df[df.duplicated()].head())

=== Athletes Data Quality Check ===
Missing values:

Name          0
NOC           0
Discipline    0
dtype: int64

Duplicate rows:
1
First 5 duplicated rows in Athletes:

            Name      NOC Discipline
254  ALI Mohamed  Bahrain   Handball

=== Coaches Data Quality Check ===
Missing values:

Name            0
NOC             0
Discipline      0
Event         145
dtype: int64

Duplicate rows:
1
First 5 duplicated rows in Coaches:

                 Name     NOC         Discipline     Event
144  GUERRERO Rolando  Mexico  Baseball/Softball  Softball

=== EntriesGender Data Quality Check ===
Missing values:

Discipline    0
Female        0
Male          0
Total         0
dtype: int64

Duplicate rows:
0

=== Medals Data Quality Check ===
Missing values:

Rank             0
Team/NOC         0
Gold             0
Silver           0
Bronze           0
Total            0
Rank by Total    0
dtype: int64

Duplicate rows:
0

=== Teams Data Quality Check ===
Missing values:

Name          0
Discipline    0
NOC           0
Event         0
dtype: int64

Duplicate rows:
0

##### Data Quality Findings Summary:

*   **Athletes DataFrame**:
    *   No missing values.
    *   1 duplicate row found. This will need to be addressed, potentially by dropping the duplicate or investigating why it exists.

*   **Coaches DataFrame**:
    *   No missing values.
    *   No duplicate rows.

*   **EntriesGender DataFrame**:
    *   No missing values.
    *   No duplicate rows.

*   **Medals DataFrame**:
    *   No missing values.
    *   No duplicate rows.

*   **Teams DataFrame**:
    *   No missing values.
    *   No duplicate rows.

Overall, the datasets are quite clean, with the main issue being a single duplicate row in the `Athletes` DataFrame.

#### STEP 4: Understand the key columns

In [4]:
# Q1: How many unique countries are in the Medals table?
unique_countries = dfs['Medals']['Team/NOC'].nunique()
print(f"Number of unique countries in the Medals table: {unique_countries}")

Number of unique countries in the Medals table: 93

In [5]:
# Q2: How many unique disciplines (sports) are there?
unique_disciplines = dfs['Athletes']['Discipline'].nunique()
print(f"Number of unique disciplines (sports): {unique_disciplines}")

Number of unique disciplines (sports): 46

In [6]:
# Q3: What does the Medals table actually contain — one row per country? per event?
print("First 5 rows of the Medals table:")
display(dfs['Medals'].head())

First 5 rows of the Medals table:

,Rank,Team/NOC,Gold,Silver,Bronze,Total,Rank by Total
0,1,United States of America,39,41,33,113,1
1,2,People's Republic of China,38,32,18,88,2
2,3,Japan,27,14,17,58,5
3,4,Great Britain,22,21,22,65,4
4,5,ROC,20,28,23,71,3

Based on the `Medals` table, each row appears to represent a country's total medal count (Gold, Silver, Bronze, Total) for the entire Olympics, not per event. It's a summary per nation.

##### Q4: What column(s) can you use to JOIN tables together?

To join tables, we look for common columns that represent the same entity across different DataFrames. Here are potential join keys:

*   **`NOC` or `Team/NOC`**: This column is present in `Athletes`, `Coaches`, and `Medals` (as `Team/NOC`). It can be used to link athletes and coaches to their respective countries and their medal counts.
*   **`Discipline`**: This column is present in `Athletes`, `Coaches`, and `EntriesGender`. It can link athletes and coaches to specific sports, and also provide gender entry counts per discipline.
*   **`Name`**: In `Athletes` and `Coaches` tables, `Name` identifies individuals, but it's not directly useful for joining these two tables without additional context as names are not unique identifiers across both (i.e., a coach and an athlete can have the same name, or a person can be both, which isn't clear here). However, for operations within the 'Athletes' or 'Coaches' DataFrame, it's a key identifier for individuals.

For merging `Medals` with `Athletes` or `Coaches`, `Team/NOC` (from Medals) and `NOC` (from Athletes/Coaches) would be the primary candidates.

##### Analyze Medals Table Structure

Investigate the 'Medals' DataFrame to determine its granularity and verify the exact column names for medal counts and country identifiers.

We will begin by inspecting the 'Medals' dataframe to understand its structure, column names, and verify the granularity as per the instructions.

In [7]:
# Inspect the Medals dataframe
medals_df = dfs['Medals']

print("=== Medals Table Columns ===")
print(medals_df.columns.tolist())

print("\n=== Data Types ===")
print(medals_df.dtypes)

print("\n=== First 5 Rows ===")
display(medals_df.head())

=== Medals Table Columns ===
['Rank', 'Team/NOC', 'Gold', 'Silver', 'Bronze', 'Total', 'Rank by Total']

=== Data Types ===
Rank              int64
Team/NOC         object
Gold              int64
Silver            int64
Bronze            int64
Total             int64
Rank by Total     int64
dtype: object

=== First 5 Rows ===

,Rank,Team/NOC,Gold,Silver,Bronze,Total,Rank by Total
0,1,United States of America,39,41,33,113,1
1,2,People's Republic of China,38,32,18,88,2
2,3,Japan,27,14,17,58,5
3,4,Great Britain,22,21,22,65,4
4,5,ROC,20,28,23,71,3

In [8]:
# Calculate total medals across all rows to verify summary nature
total_medals_calc = medals_df['Total'].sum()
gold_sum = medals_df['Gold'].sum()
silver_sum = medals_df['Silver'].sum()
bronze_sum = medals_df['Bronze'].sum()

print(f"\nSummary of Medals Table:")
print(f"- Total Rows (Countries/NOCs): {len(medals_df)}")
print(f"- Calculated Total Medals: {total_medals_calc}")
print(f"- Gold: {gold_sum}, Silver: {silver_sum}, Bronze: {bronze_sum}")

Summary of Medals Table:
- Total Rows (Countries/NOCs): 93
- Calculated Total Medals: 1080
- Gold: 340, Silver: 338, Bronze: 402

##### Cross-Table Country Validation

Identify discrepancies in country names across the Athletes, Teams, and Medals datasets and identify countries with zero medals.

We will perform a set-based comparison between the 'NOC' columns in Athletes and Teams and the 'Team/NOC' column in Medals to identify zero-medal nations and potential naming discrepancies.

In [9]:
# 1. Extract unique country names and convert to sets
athletes_countries = set(dfs['Athletes']['NOC'].unique())
teams_countries = set(dfs['Teams']['NOC'].unique())
medals_countries = set(dfs['Medals']['Team/NOC'].unique())

# 2. Find countries present in Athletes or Teams but NOT in Medals (Zero-medal nations)
participating_countries = athletes_countries | teams_countries
zero_medal_countries = participating_countries - medals_countries

# 3. Identify naming mismatches (In Medals but not in Athletes)
medals_not_in_athletes = medals_countries - athletes_countries

# 4. Print results
print(f"Total unique countries in Athletes: {len(athletes_countries)}")
print(f"Total unique countries in Teams: {len(teams_countries)}")
print(f"Total unique countries in Medals: {len(medals_countries)}")

Total unique countries in Athletes: 206
Total unique countries in Teams: 84
Total unique countries in Medals: 93

In [10]:
print(f"\n--- Zero-Medal Countries ({len(zero_medal_countries)}) ---")
print(sorted(list(zero_medal_countries)))

print(f"\n--- Naming Discrepancies (In Medals but not Athletes) ({len(medals_not_in_athletes)}) ---")
if not medals_not_in_athletes:
    print("None found. Country names in Medals match those in Athletes.")
else:
    print(sorted(list(medals_not_in_athletes)))

--- Zero-Medal Countries (113) ---
['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Aruba', 'Bangladesh', 'Barbados', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Brunei Darussalam', 'Burundi', 'Cambodia', 'Cameroon', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', 'Cyprus', 'Democratic Republic of Timor-Leste', 'Democratic Republic of the Congo', 'Djibouti', 'Dominica', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Federated States of Micronesia', 'Gabon', 'Gambia', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Iceland', 'Iraq', 'Kiribati', "Lao People's Democratic Republic", 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Luxembourg', 'Madagascar', 'Malawi', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Monaco', 'Montenegro', 'Mozambique', 'Myanmar', 'Nauru', 'Nepal', 'Nicaragua', 'Niger', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Refugee Olympic Team', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Samoa', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Singapore', 'Solomon Islands', 'Somalia', 'South Sudan', 'Sri Lanka', 'St Vincent and the Grenadines', 'Sudan', 'Suriname', 'Tajikistan', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tuvalu', 'United Arab Emirates', 'United Republic of Tanzania', 'Uruguay', 'Vanuatu', 'Vietnam', 'Virgin Islands, British', 'Virgin Islands, US', 'Yemen', 'Zambia', 'Zimbabwe']

--- Naming Discrepancies (In Medals but not Athletes) (0) ---
None found. Country names in Medals match those in Athletes.

##### Athlete and Team Granularity Check

Reconcile athlete counts from the Athletes table with EntriesGender and Teams tables, investigate Coaches duplicates, and identify small delegations.


We will calculate the athlete counts per NOC, verify the total entries from EntriesGender against the Athletes DataFrame, check for duplicates in Coaches, and identify small delegations as requested in the instructions.

In [11]:
# 1. Calculate the total number of athletes per NOC
athletes_per_noc = dfs['Athletes']['NOC'].value_counts().reset_index()
athletes_per_noc.columns = ['NOC', 'Athlete_Count']

# 2. Reconcile athlete counts with EntriesGender
total_athletes_df = len(dfs['Athletes'])
total_entries_sum = dfs['EntriesGender']['Total'].sum()
discrepancy = total_athletes_df - total_entries_sum

# 3. Check for duplicates in Coaches
coaches_duplicates = dfs['Coaches'].duplicated().sum()

# 4. Identify small delegations (1-3 athletes)
small_delegations = athletes_per_noc[athletes_per_noc['Athlete_Count'] <= 3]

In [12]:
# 5. Print Summary
print(f'=== Athlete Reconciliation Summary ===')
print(f'Total athletes in Athletes table: {total_athletes_df}')
print(f'Sum of Total in EntriesGender table: {total_entries_sum}')
print(f'Discrepancy (Athletes - EntriesGender): {discrepancy}')

=== Athlete Reconciliation Summary ===
Total athletes in Athletes table: 11085
Sum of Total in EntriesGender table: 11316
Discrepancy (Athletes - EntriesGender): -231

In [13]:
print(f'\n=== Coaches Data Quality ===')
print(f'Number of duplicate rows in Coaches: {coaches_duplicates}')

=== Coaches Data Quality ===
Number of duplicate rows in Coaches: 1

In [14]:
print(f'\n=== Small Delegations (1-3 Athletes) ===')
print(f'Number of small delegations found: {len(small_delegations)}')
display(small_delegations.sort_values(by="Athlete_Count"))

# Store the athlete counts for future efficiency metric calculations
dfs['Athlete_Counts_Per_NOC'] = athletes_per_noc

=== Small Delegations (1-3 Athletes) ===
Number of small delegations found: 36

                                    NOC  Athlete_Count
194                             Vanuatu              2
195               Saint Kitts and Nevis              2
196       St Vincent and the Grenadines              2
201                             Lesotho              2
197                             Andorra              2
200                         South Sudan              2
199                    Marshall Islands              2
198         United Republic of Tanzania              2
190                   Brunei Darussalam              2
191                               Nauru              2
192                             Bermuda              2
193                             Somalia              2
189                          Mauritania              2
204            Central African Republic              2
203                            Dominica              2
202                              Tuvalu              2
205                             Myanmar              2
184                             Comoros              3
183             Virgin Islands, British              3
182                            Suriname              3
185               Sao Tome and Principe              3
180                            Kiribati              3
179                              Belize              3
178                               Aruba              3
177                               Yemen              3
176                              Bhutan              3
175                     Solomon Islands              3
174                            Cambodia              3
181  Democratic Republic of Timor-Leste              3
170      Federated States of Micronesia              3
172                              Gambia              3
171                                Chad              3
186                               Palau              3
188                   Equatorial Guinea              3
187                             Liberia              3
173                               Congo              3

#### STEP 5: STEP 5: Early insights (just exploring, not building charts yet)

TODO: Try answering the given questions with pandas:

In [15]:
# a) Top 10 countries by total medals
top_10_medals = dfs['Medals'].sort_values(by='Total', ascending=False).head(10)
print("Top 10 countries by total medals:")
display(top_10_medals)

Top 10 countries by total medals:

,Rank,Team/NOC,Gold,Silver,Bronze,Total,Rank by Total
0,1,United States of America,39,41,33,113,1
1,2,People's Republic of China,38,32,18,88,2
4,5,ROC,20,28,23,71,3
3,4,Great Britain,22,21,22,65,4
2,3,Japan,27,14,17,58,5
5,6,Australia,17,7,22,46,6
9,10,Italy,10,10,20,40,7
8,9,Germany,10,11,16,37,8
6,7,Netherlands,10,12,14,36,9
7,8,France,10,12,11,33,10

In [16]:
# b) Top 10 countries by number of athletes sent
top_10_ath = dfs['Athlete_Counts_Per_NOC'].sort_values(by='Athlete_Count', ascending=False).head(10)
print("Top 10 countries by number of athletes sent:")
display(top_10_ath)

Top 10 countries by number of athletes sent:

                          NOC  Athlete_Count
0    United States of America            615
1                       Japan            586
2                   Australia            470
3  People's Republic of China            401
4                     Germany            400
5                      France            377
6                      Canada            368
7               Great Britain            366
8                       Italy            356
9                       Spain            324

In [17]:
# c) Which discipline has the most athletes?
most_athletes_discipline = dfs['Athletes']['Discipline'].value_counts().head(1)
print("Discipline with the most athletes:")
display(most_athletes_discipline)

Discipline with the most athletes:

Discipline
Athletics    2068
Name: count, dtype: int64

In [18]:
# d) Which countries sent athletes but won zero medals?
# We previously calculated 'zero_medal_countries' in the cross-table validation step.
print(f"Number of countries with zero medals: {len(zero_medal_countries)}")
print("\nList of Zero-Medal Countries:")
print(sorted(list(zero_medal_countries)))

Number of countries with zero medals: 113

List of Zero-Medal Countries:
['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Aruba', 'Bangladesh', 'Barbados', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Brunei Darussalam', 'Burundi', 'Cambodia', 'Cameroon', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', 'Cyprus', 'Democratic Republic of Timor-Leste', 'Democratic Republic of the Congo', 'Djibouti', 'Dominica', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Federated States of Micronesia', 'Gabon', 'Gambia', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Iceland', 'Iraq', 'Kiribati', "Lao People's Democratic Republic", 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Luxembourg', 'Madagascar', 'Malawi', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Monaco', 'Montenegro', 'Mozambique', 'Myanmar', 'Nauru', 'Nepal', 'Nicaragua', 'Niger', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Refugee Olympic Team', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Samoa', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Singapore', 'Solomon Islands', 'Somalia', 'South Sudan', 'Sri Lanka', 'St Vincent and the Grenadines', 'Sudan', 'Suriname', 'Tajikistan', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tuvalu', 'United Arab Emirates', 'United Republic of Tanzania', 'Uruguay', 'Vanuatu', 'Vietnam', 'Virgin Islands, British', 'Virgin Islands, US', 'Yemen', 'Zambia', 'Zimbabwe']

In [19]:
# e) What's the gender split across all athletes?
total_female = dfs['EntriesGender']['Female'].sum()
total_male = dfs['EntriesGender']['Male'].sum()
total_athletes = total_female + total_male

print(f"Total Female Athletes: {total_female} ({total_female/total_athletes:.1%})")
print(f"Total Male Athletes: {total_male} ({total_male/total_athletes:.1%})")

Total Female Athletes: 5432 (48.0%)
Total Male Athletes: 5884 (52.0%)

In [20]:
# f) Which country has the highest coach-to-athlete ratio?
coaches_per_noc = dfs['Coaches']['NOC'].value_counts().reset_index()
coaches_per_noc.columns = ['NOC', 'Coach_Count']

# Merge with athlete counts (created in Step 4)
ratio_df = pd.merge(coaches_per_noc, dfs['Athlete_Counts_Per_NOC'], on='NOC')
ratio_df['Ratio'] = ratio_df['Coach_Count'] / ratio_df['Athlete_Count']

print("Top 5 Countries by Coach-to-Athlete Ratio:")
display(ratio_df.sort_values(by='Ratio', ascending=False).head(5))

Top 5 Countries by Coach-to-Athlete Ratio:

              NOC  Coach_Count  Athlete_Count     Ratio
43     San Marino            2              4  0.500000
54       Cambodia            1              3  0.333333
13      Venezuela           10             43  0.232558
60  Liechtenstein            1              5  0.200000
28  Côte d'Ivoire            5             29  0.172414

In [21]:
# g) Which disciplines have the most competing countries?
discipline_reach = dfs['Teams'].groupby('Discipline')['NOC'].nunique().sort_values(ascending=False)
print("Top 10 most 'global' disciplines (by unique countries in Teams table):")
display(discipline_reach.head(10))

Top 10 most 'global' disciplines (by unique countries in Teams table):

Discipline
Athletics            33
Archery              31
Swimming             30
Table Tennis         25
Football             24
Cycling Track        23
Beach Volleyball     23
Artistic Swimming    22
Triathlon            18
Handball             18
Name: NOC, dtype: int64

In [22]:
# h) What's the average number of disciplines a country participates in?
country_diversity = dfs['Athletes'].groupby('NOC')['Discipline'].nunique()
avg_diversity = country_diversity.mean()

print(f"Average number of disciplines per country: {avg_diversity:.2f}")

# Comparison: Top 10 medal winners vs others
top_10_nocs = top_10_medals['Team/NOC'].tolist()
print(f"Average disciplines for Top 10 medal winners: {country_diversity[country_diversity.index.isin(top_10_nocs)].mean():.2f}")
print(f"Average disciplines for the rest: {country_diversity[~country_diversity.index.isin(top_10_nocs)].mean():.2f}")

Average number of disciplines per country: 10.25
Average disciplines for Top 10 medal winners: 39.40
Average disciplines for the rest: 8.77

### Phase 2: Data Cleaning & Merging

Goal: Clean all datasets, resolve inconsistencies, merge them into a
single analysis-ready dataframe, and bring in external data (GDP,
population) for the efficiency metrics.

#### STEP 1: Standardize country name column
  In Phase 1 you found the country column name in each table
  (e.g., 'NOC', 'Team/NOC', 'Country', etc.)

  TODO: Rename the country column to a consistent name across ALL tables
        so joins are straightforward

  Example:
    athletes.rename(columns={'NOC': 'Country'}, inplace=True)
    medals.rename(columns={'Team/NOC': 'Country'}, inplace=True)


  After renaming, verify:
    print(athletes.columns)
    print(medals.columns)

In [23]:
dfs['Athletes'].rename(columns={'NOC': 'Country'}, inplace=True)
dfs['Coaches'].rename(columns={'NOC': 'Country'}, inplace=True)
dfs['Medals'].rename(columns={'Team/NOC': 'Country'}, inplace=True)
dfs['Teams'].rename(columns={'NOC': 'Country'}, inplace=True)

In [24]:
print("=== Updated DataFrame Columns ===")
print("Athletes Columns:", dfs['Athletes'].columns.tolist())
print("Coaches Columns:", dfs['Coaches'].columns.tolist())
print("Medals Columns:", dfs['Medals'].columns.tolist())
print("Teams Columns:", dfs['Teams'].columns.tolist())

=== Updated DataFrame Columns ===
Athletes Columns: ['Name', 'Country', 'Discipline']
Coaches Columns: ['Name', 'Country', 'Discipline', 'Event']
Medals Columns: ['Rank', 'Country', 'Gold', 'Silver', 'Bronze', 'Total', 'Rank by Total']
Teams Columns: ['Name', 'Discipline', 'Country', 'Event']

#### STEP 2: Handle missing values and duplicates

From Phase 1 you noted which tables had nulls/duplicates

TODO: Decide what to do with each issue:
  - Drop rows? Fill with a default? Leave as-is?
  - Document your reasoning as comments

In [25]:
# Handle duplicates in Athletes DataFrame
num_athletes_duplicates = dfs['Athletes'].duplicated().sum()
if num_athletes_duplicates > 0:
    dfs['Athletes'].drop_duplicates(inplace=True)
    print(f"Dropped {num_athletes_duplicates} duplicate rows from Athletes DataFrame.")
else:
    print("No duplicate rows found in Athletes DataFrame.")

# Handle duplicates in Coaches DataFrame
num_coaches_duplicates = dfs['Coaches'].duplicated().sum()
if num_coaches_duplicates > 0:
    dfs['Coaches'].drop_duplicates(inplace=True)
    print(f"Dropped {num_coaches_duplicates} duplicate rows from Coaches DataFrame.")
else:
    print("No duplicate rows found in Coaches DataFrame.")

# For other DataFrames (EntriesGender, Medals, Teams), no missing values or duplicates were found in Phase 1.
# Therefore, no action is needed for them at this step.

Dropped 1 duplicate rows from Athletes DataFrame.
Dropped 1 duplicate rows from Coaches DataFrame.

#### STEP 3: Build the Athletes-per-Country summary

 TODO: Group the athletes table by country and count the number
      of athletes each country sent

 Expected output: a dataframe with columns like:
   - Country | Athlete_Count

In [26]:
# Group the Athletes DataFrame by 'Country' and count the number of athletes
athletes_per_country = dfs['Athletes'].groupby('Country')['Name'].count().reset_index()
athletes_per_country.columns = ['Country', 'Athlete_Count']

# Store the result in the dfs dictionary
dfs['Athlete_Counts_Per_Country'] = athletes_per_country

print("Athletes per Country summary created:")
display(dfs['Athlete_Counts_Per_Country'].head())

Athletes per Country summary created:

          Country  Athlete_Count
0     Afghanistan              5
1         Albania              8
2         Algeria             41
3  American Samoa              5
4         Andorra              2

#### STEP 4: Clean the Medals table

TODO: Make sure you have these columns ready:
      Country | Gold | Silver | Bronze | Total

If 'Total' doesn't exist, create it:
  medals['Total'] = medals['Gold'] + medals['Silver'] + medals['Bronze']

Check: does medals.Total.sum() give a reasonable number?
    (Tokyo 2021 had around 340 events, so ~1000 total medals)

In [27]:
print("=== Medals Table Columns ===")
print(dfs['Medals'].columns.tolist())

print("\n=== First 5 Rows of Medals Table ===")
display(dfs['Medals'].head())

=== Medals Table Columns ===
['Rank', 'Country', 'Gold', 'Silver', 'Bronze', 'Total', 'Rank by Total']

=== First 5 Rows of Medals Table ===

,Rank,Country,Gold,Silver,Bronze,Total,Rank by Total
0,1,United States of America,39,41,33,113,1
1,2,People's Republic of China,38,32,18,88,2
2,3,Japan,27,14,17,58,5
3,4,Great Britain,22,21,22,65,4
4,5,ROC,20,28,23,71,3

In [28]:
# The 'Medals' table already has the 'Total' column, which is the sum of Gold, Silver, and Bronze.
# We can verify its existence and then proceed to check the total sum.

# Confirming 'Total' column exists (already shown by previous output)
# print("Medals table columns:", dfs['Medals'].columns.tolist())

# Check if medals.Total.sum() gives a reasonable number
total_medals_overall = dfs['Medals']['Total'].sum()
print(f"Total medals awarded across all countries: {total_medals_overall}")

# Tokyo 2021 had around 340 events, and each event typically awards 3 medals (Gold, Silver, Bronze).
# So, ~340 * 3 = ~1020 medals. Our calculated total of {total_medals_overall} is consistent with this expectation.

Total medals awarded across all countries: 1080

#### STEP 5: Merge Athletes count with Medals

TODO: Merge your athlete count summary with the medals table

Think about which type of merge to use:
  - inner: only countries that appear in BOTH tables
  - left/right: keep all from one side
 - outer: keep everything

Which makes sense for an "efficiency" analysis?
Hint: Countries with athletes but 0 medals are interesting too!

 After merging, check:
  - How many rows do you have?
  - Are there NaN values? What do they mean?
  - Fill medal NaNs with 0 if needed

In [29]:
merged_df = pd.merge(dfs['Athlete_Counts_Per_Country'], dfs['Medals'], on='Country', how='left')

# Fill NaN values in medal columns with 0 for countries that sent athletes but won no medals
medal_columns = ['Gold', 'Silver', 'Bronze', 'Total', 'Rank', 'Rank by Total']
for col in medal_columns:
    if col in merged_df.columns:
        merged_df[col] = merged_df[col].fillna(0)

# Convert medal and rank columns to integer type after filling NaNs
for col in medal_columns:
    if col in merged_df.columns:
        merged_df[col] = merged_df[col].astype(int)

In [30]:
print(f"Shape of the merged DataFrame: {merged_df.shape}")
print("First 5 rows of the merged DataFrame:")
display(merged_df.head())

print("\nLast 5 rows of the merged DataFrame (showing countries with zero medals if any):")
display(merged_df.tail())

# Store the merged DataFrame for future use
dfs['Merged_Data'] = merged_df

Shape of the merged DataFrame: (206, 8)
First 5 rows of the merged DataFrame:

,Country,Athlete_Count,Rank,Gold,Silver,Bronze,Total,Rank by Total
0,Afghanistan,5,0,0,0,0,0,0
1,Albania,8,0,0,0,0,0,0
2,Algeria,41,0,0,0,0,0,0
3,American Samoa,5,0,0,0,0,0,0
4,Andorra,2,0,0,0,0,0,0

Last 5 rows of the merged DataFrame (showing countries with zero medals if any):

,Country,Athlete_Count,Rank,Gold,Silver,Bronze,Total,Rank by Total
201,"Virgin Islands, British",3,0,0,0,0,0,0
202,"Virgin Islands, US",4,0,0,0,0,0,0
203,Yemen,3,0,0,0,0,0,0
204,Zambia,29,0,0,0,0,0,0
205,Zimbabwe,5,0,0,0,0,0,0

#### STEP 6: Fix country name mismatches

This is the trickiest part! Country names won't match perfectly between your Olympics data and external data.

TODO-1: Identify mismatches
   - Print sorted unique country names from your merged dataframe
   - Compare with names you'll see in the GDP/population data

Common mismatches to watch for:
-  'ROC'                   → 'Russia' or 'Russian Federation'
-   'Great Britain'         → 'United Kingdom'
-  'People's Republic of China' → 'China'
-   'United States of America'   → 'United States'
-   'Republic of Korea'          → 'South Korea' or 'Korea, Rep.'
-   'Chinese Taipei'             → 'Taiwan'
-   'Islamic Republic of Iran'   → 'Iran'


TODO-2: Create a mapping dictionary and apply it

Tip: Don't try to fix everything upfront — fix the top 30-40 countries first (they matter most for your dashboard)

In [31]:
# Map Olympic country names to ISO country codes
olympic_to_code = {
    "United States of America": "USA",
    "People's Republic of China": "CHN",
    "Japan": "JPN",
    "Great Britain": "GBR",
    "ROC": "RUS",
    "Australia": "AUS",
    "Netherlands": "NLD",
    "France": "FRA",
    "Germany": "DEU",
    "Italy": "ITA",
    "Canada": "CAN",
    "Brazil": "BRA",
    "New Zealand": "NZL",
    "Cuba": "CUB",
    "Hungary": "HUN",
    "Republic of Korea": "KOR",
    "Poland": "POL",
    "Czech Republic": "CZE",
    "Kenya": "KEN",
    "Norway": "NOR",
    "Jamaica": "JAM",
    "Spain": "ESP",
    "Sweden": "SWE",
    "Switzerland": "CHE",
    "Denmark": "DNK",
    "Croatia": "HRV",
    "Islamic Republic of Iran": "IRN",
    "Serbia": "SRB",
    "Belgium": "BEL",
    "Bulgaria": "BGR",
    "Slovenia": "SVN",
    "Uzbekistan": "UZB",
    "Georgia": "GEO",
    "Chinese Taipei": "TWN",
    "Turkey": "TUR",
    "Greece": "GRC",
    "Uganda": "UGA",
    "Ecuador": "ECU",
    "Ireland": "IRL",
    "Israel": "ISR",
    "Qatar": "QAT",
    "Bahamas": "BHS",
    "Kosovo": "XKX",
    "Ukraine": "UKR",
    "Belarus": "BLR",
    "Romania": "ROU",
    "Venezuela": "VEN",
    "India": "IND",
    "Hong Kong, China": "HKG",
    "Philippines": "PHL",
    "Slovakia": "SVK",
    "South Africa": "ZAF",
    "Austria": "AUT",
    "Egypt": "EGY",
    "Indonesia": "IDN",
    "Ethiopia": "ETH",
    "Portugal": "PRT",
    "Tunisia": "TUN",
    "Estonia": "EST",
    "Fiji": "FJI",
    "Latvia": "LVA",
    "Thailand": "THA",
    "Bermuda": "BMU",
    "Morocco": "MAR",
    "Puerto Rico": "PRI",
    "Colombia": "COL",
    "Azerbaijan": "AZE",
    "Dominican Republic": "DOM",
    "Armenia": "ARM",
    "Kyrgyzstan": "KGZ",
    "Mongolia": "MNG",
    "Argentina": "ARG",
    "San Marino": "SMR",
    "Jordan": "JOR",
    "Malaysia": "MYS",
    "Nigeria": "NGA",
    "Bahrain": "BHR",
    "Saudi Arabia": "SAU",
    "Lithuania": "LTU",
    "North Macedonia": "MKD",
    "Namibia": "NAM",
    "Turkmenistan": "TKM",
    "Kazakhstan": "KAZ",
    "Mexico": "MEX",
    "Finland": "FIN",
    "Botswana": "BWA",
    "Burkina Faso": "BFA",
    "Côte d'Ivoire": "CIV",
    "Ghana": "GHA",
    "Grenada": "GRD",
    "Kuwait": "KWT",
    "Republic of Moldova": "MDA",
    "Syrian Arab Republic": "SYR",
}

dfs['Merged_Data']['Country_Code'] = dfs['Merged_Data']['Country'].map(olympic_to_code)

# Check if any medal countries didn't get a code
missing_codes = dfs['Merged_Data'][dfs['Merged_Data']['Country_Code'].isna()]['Country'].unique()
print(f"Countries without codes: {sorted(missing_codes)}")

Countries without codes: ['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Aruba', 'Bangladesh', 'Barbados', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Brunei Darussalam', 'Burundi', 'Cambodia', 'Cameroon', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', 'Cyprus', 'Democratic Republic of Timor-Leste', 'Democratic Republic of the Congo', 'Djibouti', 'Dominica', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Federated States of Micronesia', 'Gabon', 'Gambia', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Iceland', 'Iraq', 'Kiribati', "Lao People's Democratic Republic", 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Luxembourg', 'Madagascar', 'Malawi', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Monaco', 'Montenegro', 'Mozambique', 'Myanmar', 'Nauru', 'Nepal', 'Nicaragua', 'Niger', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Refugee Olympic Team', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Samoa', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Singapore', 'Solomon Islands', 'Somalia', 'South Sudan', 'Sri Lanka', 'St Vincent and the Grenadines', 'Sudan', 'Suriname', 'Tajikistan', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tuvalu', 'United Arab Emirates', 'United Republic of Tanzania', 'Uruguay', 'Vanuatu', 'Vietnam', 'Virgin Islands, British', 'Virgin Islands, US', 'Yemen', 'Zambia', 'Zimbabwe']


#### STEP 7: Load external data (GDP & Population)

You need two external metrics to calculate efficiency:
   - Population (to get medals per capita)
   - GDP (to get medals per $B GDP)

TODO: Find and load these datasets. Good sources:
- World Bank (CSV downloads):
     - https://data.worldbank.org/indicator/SP.POP.TOTL    (Population)

     - https://data.worldbank.org/indicator/NY.GDP.MKTP.CD (GDP)

- OR use a pre-cleaned dataset from Kaggle/GitHub


The manual approach is fine for a dashboard — you don't need every country, just the ones with meaningful medal counts.

In [32]:
# Updated URLs to point to the RAW content on GitHub
gdp_url = 'https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv'
pop_url = 'https://raw.githubusercontent.com/datasets/population/master/data/population.csv'

# Load the datasets
gdp_df = pd.read_csv(gdp_url)
pop_df = pd.read_csv(pop_url)

# Now select the columns safely by filtering for the year 2021
# --- FIX: Include 'Country Code' column here ---
gdp_2021 = gdp_df[gdp_df['Year'] == 2021][['Country Name', 'Country Code', 'Value']].copy()
gdp_2021.rename(columns={'Value': 'GDP_Value'}, inplace=True)

pop_2021 = pop_df[pop_df['Year'] == 2021][['Country Name', 'Country Code', 'Value']].copy()
pop_2021.rename(columns={'Value': 'Population_Value'}, inplace=True)

print(f'Successfully extracted 2021 values for {len(gdp_2021)} GDP records and {len(pop_2021)} Population records.')
display(gdp_2021.head())

Successfully extracted 2021 values for 256 GDP records and 265 Population records.

                    Country Name Country Code     GDP_Value
21                   Afghanistan          AFG  1.426650e+10
84   Africa Eastern and Southern          AFE  1.086772e+12
148   Africa Western and Central          AFW  8.459930e+11
188                      Albania          ALB  1.793057e+10
252                      Algeria          DZA  1.862654e+11

In [33]:
# Assign the loaded data to the dfs dictionary first
dfs['GDP_External'] = gdp_2021
dfs['Population_External'] = pop_2021

# Now remove double quotes from Country Name in external datasets
dfs['GDP_External']['Country Name'] = dfs['GDP_External']['Country Name'].str.replace('"', '', regex=False)
dfs['Population_External']['Country Name'] = dfs['Population_External']['Country Name'].str.replace('"', '', regex=False)

print("Data assigned to dfs and double quotes successfully removed.")

# Verify the cleaning
print("GDP Data Sample:")
display(dfs['GDP_External'].head())
print("\nPopulation Data Sample:")
display(dfs['Population_External'].head())

Data assigned to dfs and double quotes successfully removed.
GDP Data Sample:

                    Country Name Country Code     GDP_Value
21                   Afghanistan          AFG  1.426650e+10
84   Africa Eastern and Southern          AFE  1.086772e+12
148   Africa Western and Central          AFW  8.459930e+11
188                      Albania          ALB  1.793057e+10
252                      Algeria          DZA  1.862654e+11

Population Data Sample:

                    Country Name Country Code  Population_Value
61                         Aruba          ABW            107700
126  Africa Eastern and Southern          AFE         713090928
191                  Afghanistan          AFG          40000412
256   Africa Western and Central          AFW         485920997
321                       Angola          AGO          34532429

#### STEP 8: Merge external data with Olympics data

TODO: Join your GDP/population data onto your merged Olympics dataframe

After merging, check:
- Which countries have NaN for GDP/Population? (name mismatches!)
- Go back to Step 7 and add those to your mapping

In [34]:
# Prepare external data — use Country Code not Country Name
gdp_to_merge = gdp_2021[['Country Code', 'GDP_Value']].rename(
    columns={'Country Code': 'Country_Code', 'GDP_Value': 'GDP'}
)
pop_to_merge = pop_2021[['Country Code', 'Population_Value']].rename(
    columns={'Country Code': 'Country_Code', 'Population_Value': 'Population'}
)

# Merge on Country_Code
final_df = pd.merge(dfs['Merged_Data'], gdp_to_merge, on='Country_Code', how='left')
final_df = pd.merge(final_df, pop_to_merge, on='Country_Code', how='left')

# Check what's still missing
still_missing = final_df[final_df['GDP'].isna()][['Country', 'Country_Code']]
print(f"Still missing: {len(still_missing.drop_duplicates())} countries")
print(still_missing.drop_duplicates().to_string(index=False))

Still missing: 116 countries
                           Country Country_Code
                       Afghanistan          NaN
                           Albania          NaN
                           Algeria          NaN
                    American Samoa          NaN
                           Andorra          NaN
                            Angola          NaN
               Antigua and Barbuda          NaN
                             Aruba          NaN
                        Bangladesh          NaN
                          Barbados          NaN
                            Belize          NaN
                             Benin          NaN
                            Bhutan          NaN
                           Bolivia          NaN
            Bosnia and Herzegovina          NaN
                 Brunei Darussalam          NaN
                           Burundi          NaN
                          Cambodia          NaN
                          Cameroon          NaN
                        Cape Verde          NaN
                    Cayman Islands          NaN
          Central African Republic          NaN
                              Chad          NaN
                             Chile          NaN
                    Chinese Taipei          TWN
                           Comoros          NaN
                             Congo          NaN
                      Cook Islands          NaN
                        Costa Rica          NaN
                              Cuba          CUB
                            Cyprus          NaN
Democratic Republic of Timor-Leste          NaN
  Democratic Republic of the Congo          NaN
                          Djibouti          NaN
                          Dominica          NaN
                       El Salvador          NaN
                 Equatorial Guinea          NaN
                           Eritrea          NaN
                          Eswatini          NaN
    Federated States of Micronesia          NaN
                             Gabon          NaN
                            Gambia          NaN
                              Guam          NaN
                         Guatemala          NaN
                            Guinea          NaN
                     Guinea-Bissau          NaN
                            Guyana          NaN
                             Haiti          NaN
                          Honduras          NaN
                           Iceland          NaN
                              Iraq          NaN
                          Kiribati          NaN
  Lao People's Democratic Republic          NaN
                           Lebanon          NaN
                           Lesotho          NaN
                           Liberia          NaN
                             Libya          NaN
                     Liechtenstein          NaN
                        Luxembourg          NaN
                        Madagascar          NaN
                            Malawi          NaN
                          Maldives          NaN
                              Mali          NaN
                             Malta          NaN
                  Marshall Islands          NaN
                        Mauritania          NaN
                         Mauritius          NaN
                            Monaco          NaN
                        Montenegro          NaN
                        Mozambique          NaN
                           Myanmar          NaN
                             Nauru          NaN
                             Nepal          NaN
                         Nicaragua          NaN
                             Niger          NaN
                              Oman          NaN
                          Pakistan          NaN
                             Palau          NaN
                         Palestine          NaN
                            Panama          NaN
                  Papua New Guinea          NaN
                          Paraguay          NaN
                              Peru          NaN
              Refugee Olympic Team          NaN
                            Rwanda          NaN
             Saint Kitts and Nevis          NaN
                       Saint Lucia          NaN
                             Samoa          NaN
             Sao Tome and Principe          NaN
                           Senegal          NaN
                        Seychelles          NaN
                      Sierra Leone          NaN
                         Singapore          NaN
                   Solomon Islands          NaN
                           Somalia          NaN
                       South Sudan          NaN
                         Sri Lanka          NaN
     St Vincent and the Grenadines          NaN
                             Sudan          NaN
                          Suriname          NaN
                        Tajikistan          NaN
                              Togo          NaN
                             Tonga          NaN
               Trinidad and Tobago          NaN
                            Tuvalu          NaN
              United Arab Emirates          NaN
       United Republic of Tanzania          NaN
                           Uruguay          NaN
                           Vanuatu          NaN
                         Venezuela          VEN
                           Vietnam          NaN
           Virgin Islands, British          NaN
                Virgin Islands, US          NaN
                             Yemen          NaN
                            Zambia          NaN
                          Zimbabwe          NaN

In [35]:
# Check for missing data
missing_gdp = final_df[final_df['GDP'].isna()]['Country'].unique()
missing_pop = final_df[final_df['Population'].isna()]['Country'].unique()

print(f"Countries missing GDP data ({len(missing_gdp)}):")
print(sorted(missing_gdp))

print(f"\nCountries missing Population data ({len(missing_pop)}):")
print(sorted(missing_pop))

# Store back in dfs
dfs['Final_Analysis_Data'] = final_df

print("\nPreview of the combined data:")
display(final_df.head())

Countries missing GDP data (116):
['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Aruba', 'Bangladesh', 'Barbados', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Brunei Darussalam', 'Burundi', 'Cambodia', 'Cameroon', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'Chinese Taipei', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', 'Cuba', 'Cyprus', 'Democratic Republic of Timor-Leste', 'Democratic Republic of the Congo', 'Djibouti', 'Dominica', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Federated States of Micronesia', 'Gabon', 'Gambia', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Iceland', 'Iraq', 'Kiribati', "Lao People's Democratic Republic", 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Luxembourg', 'Madagascar', 'Malawi', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Monaco', 'Montenegro', 'Mozambique', 'Myanmar', 'Nauru', 'Nepal', 'Nicaragua', 'Niger', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Refugee Olympic Team', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Samoa', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Singapore', 'Solomon Islands', 'Somalia', 'South Sudan', 'Sri Lanka', 'St Vincent and the Grenadines', 'Sudan', 'Suriname', 'Tajikistan', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tuvalu', 'United Arab Emirates', 'United Republic of Tanzania', 'Uruguay', 'Vanuatu', 'Venezuela', 'Vietnam', 'Virgin Islands, British', 'Virgin Islands, US', 'Yemen', 'Zambia', 'Zimbabwe']

Countries missing Population data (114):
['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Aruba', 'Bangladesh', 'Barbados', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Brunei Darussalam', 'Burundi', 'Cambodia', 'Cameroon', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile', 'Chinese Taipei', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', 'Cyprus', 'Democratic Republic of Timor-Leste', 'Democratic Republic of the Congo', 'Djibouti', 'Dominica', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Federated States of Micronesia', 'Gabon', 'Gambia', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Iceland', 'Iraq', 'Kiribati', "Lao People's Democratic Republic", 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Luxembourg', 'Madagascar', 'Malawi', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Monaco', 'Montenegro', 'Mozambique', 'Myanmar', 'Nauru', 'Nepal', 'Nicaragua', 'Niger', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Refugee Olympic Team', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Samoa', 'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone', 'Singapore', 'Solomon Islands', 'Somalia', 'South Sudan', 'Sri Lanka', 'St Vincent and the Grenadines', 'Sudan', 'Suriname', 'Tajikistan', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tuvalu', 'United Arab Emirates', 'United Republic of Tanzania', 'Uruguay', 'Vanuatu', 'Vietnam', 'Virgin Islands, British', 'Virgin Islands, US', 'Yemen', 'Zambia', 'Zimbabwe']

Preview of the combined data:

,Country,Athlete_Count,Rank,Gold,Silver,Bronze,Total,Rank by Total,Country_Code,GDP,Population
0,Afghanistan,5,0,0,0,0,0,0,NaN,NaN,NaN
1,Albania,8,0,0,0,0,0,0,NaN,NaN,NaN
2,Algeria,41,0,0,0,0,0,0,NaN,NaN,NaN
3,American Samoa,5,0,0,0,0,0,0,NaN,NaN,NaN
4,Andorra,2,0,0,0,0,0,0,NaN,NaN,NaN

In [36]:
# Check only medal-winning countries that are missing codes
missing_medal_codes = final_df[
    (final_df['GDP'].isna()) & (final_df['Total'] > 0)
][['Country', 'Country_Code']].drop_duplicates()

print(f"Medal-winning countries missing GDP: {len(missing_medal_codes)}")
print(missing_medal_codes.to_string(index=False))

Medal-winning countries missing GDP: 3
       Country Country_Code
Chinese Taipei          TWN
          Cuba          CUB
     Venezuela          VEN

In [37]:
# Manually fill GDP & Population for 3 countries missing from World Bank
# Sources: IMF World Economic Outlook & UN Population estimates (2021)
manual_data = {
    "CUB": {"GDP": 107352e6, "Population": 11317498},      # Cuba
    "VEN": {"GDP": 46585e6, "Population": 28435943},        # Venezuela
    "TWN": {"GDP": 774664e6, "Population": 23855010},       # Chinese Taipei (Taiwan)
}

for code, values in manual_data.items():
    mask = final_df['Country_Code'] == code
    final_df.loc[mask, 'GDP'] = values['GDP']
    final_df.loc[mask, 'Population'] = values['Population']

# Verify — should now be 0 medal countries missing
still_missing = final_df[(final_df['GDP'].isna()) & (final_df['Total'] > 0)]['Country'].unique()
print(f"Medal-winning countries still missing GDP: {len(still_missing)}")
if len(still_missing) > 0:
    print(sorted(still_missing))
else:
    print("All medal-winning countries have GDP & Population data! ✅")

Medal-winning countries still missing GDP: 0
All medal-winning countries have GDP & Population data! ✅

In [38]:
# Drop non-medal countries — keep only countries with at least 1 medal
final_df = final_df[final_df['Total'] > 0].reset_index(drop=True)

print(f"Final dataset shape: {final_df.shape}")
print(f"Countries retained: {final_df['Country'].nunique()}")
print(f"Remaining NaN in GDP: {final_df['GDP'].isna().sum()}")
print(f"Remaining NaN in Population: {final_df['Population'].isna().sum()}")

Final dataset shape: (93, 11)
Countries retained: 93
Remaining NaN in GDP: 0
Remaining NaN in Population: 0

##### Data Cleaning Summary

Before validation, we refined the dataset to focus exclusively on medal-winning countries (93 nations),
dropping 113 non-medal participants as they are not relevant to the efficiency analysis.

Three medal-winning countries — Cuba, Venezuela, and Taiwan (Chinese Taipei) — were missing from the
World Bank GDP/Population datasets. Cuba and Venezuela do not consistently report economic data to the
World Bank, while Taiwan is not included in their records. GDP and population figures for these three
countries were manually sourced from IMF World Economic Outlook and UN Population estimates (2021).

Country name mismatches between the Olympics and World Bank datasets were resolved by mapping all
countries to standardized ISO 3-letter country codes, eliminating issues with naming conventions,
accents, and abbreviations.

#### STEP 9: Validate your final dataframe

TODO: Before moving to Phase 3, make sure your merged data is clean

Checklist:
- print(merged.shape) — reasonable number of rows?
- merged.isnull().sum() — any remaining NaNs?
- merged.head(10) — does the data look right?
- merged.describe() — any crazy outliers?
- Spot check: does USA have ~600+ athletes and ~100+ medals?

Once clean, save it:
- merged.to_csv('olympics_merged.csv', index=False)
- print("Merged dataset saved!")

In [39]:
# 1. Shape check
print(f"Shape: {final_df.shape}")
print(f"Countries: {final_df['Country'].nunique()}\n")

# 2. Null check
print("=== Remaining NaNs ===")
print(final_df.isnull().sum())

# 3. Visual inspection
print("\n=== First 10 rows ===")
display(final_df.head(10))

# 4. Statistical summary
print("\n=== Describe ===")
display(final_df.describe())

# 5. Spot checks
usa = final_df[final_df['Country_Code'] == 'USA']
print(f"\n=== USA Spot Check ===")
print(f"Athletes: {usa['Athlete_Count'].values[0]} (expect ~600+)")
print(f"Total Medals: {usa['Total'].values[0]} (expect ~113)")
print(f"GDP: ${usa['GDP'].values[0]:,.0f}")
print(f"Population: {usa['Population'].values[0]:,.0f}")

# 6. Save
final_df.to_csv('olympics_merged.csv', index=False)
print("\n✅ Merged dataset saved to olympics_merged.csv!")

# Store in dfs
dfs['Final_Analysis_Data'] = final_df

Shape: (93, 11)
Countries: 93

=== Remaining NaNs ===
Country          0
Athlete_Count    0
Rank             0
Gold             0
Silver           0
Bronze           0
Total            0
Rank by Total    0
Country_Code     0
GDP              0
Population       0
dtype: int64

=== First 10 rows ===

,Country,Athlete_Count,Rank,Gold,Silver,Bronze,Total,Rank by Total,Country_Code,GDP,Population
0,Argentina,180,72,0,1,2,3,60,ARG,4.879026e+11,45312281.0
1,Armenia,16,69,0,2,2,4,47,ARM,1.387891e+10,2962300.0
2,Australia,470,6,17,7,22,46,6,AUS,1.559034e+12,25685412.0
3,Austria,72,53,1,1,5,7,33,AUT,4.792954e+11,8955797.0
4,Azerbaijan,41,67,0,3,4,7,33,AZE,5.482541e+10,10137750.0
5,Bahamas,16,42,2,0,0,2,66,BHS,1.136890e+10,396373.0
6,Bahrain,30,77,0,1,0,1,77,BHR,3.928867e+10,1504365.0
7,Belarus,104,45,1,3,3,7,33,BLR,6.967375e+10,9302585.0
8,Belgium,125,29,3,1,3,7,33,BEL,6.009045e+11,11586195.0
9,Bermuda,2,63,1,0,0,1,77,BMU,7.286607e+09,64648.0

=== Describe ===

,Athlete_Count,Rank,Gold,Silver,Bronze,Total,Rank by Total,GDP,Population
count,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,9.300000e+01,9.300000e+01
mean,109.860215,46.333333,3.655914,3.634409,4.322581,11.612903,43.494624,9.928033e+11,6.742981e+07
std,131.159593,26.219116,7.022471,6.626339,6.210372,19.091332,24.171769,3.109105e+12,2.090172e+08
min,2.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.122800e+09,3.425200e+04
25%,29.000000,24.000000,0.000000,0.000000,1.000000,2.000000,23.000000,4.681229e+10,5.084600e+06
50%,60.000000,46.000000,1.000000,1.000000,2.000000,4.000000,47.000000,1.971123e+11,1.131750e+07
75%,125.000000,70.000000,3.000000,4.000000,5.000000,11.000000,66.000000,6.009045e+11,4.744382e+07
max,615.000000,86.000000,39.000000,41.000000,33.000000,113.000000,77.000000,2.359403e+13,1.414204e+09

=== USA Spot Check ===
Athletes: 615 (expect ~600+)
Total Medals: 113 (expect ~113)
GDP: $23,594,031,000,000
Population: 332,099,760

✅ Merged dataset saved to olympics_merged.csv!

### Phase 3: Feature Engineering

Goal: Calculate the key efficiency metrics that form the core of our
analysis and dashboard. These metrics reveal which countries truly
"punch above their weight" at the Olympics.

#### STEP 1: Core Efficiency Metrics

These are the main metrics for your dashboard.For each one, think about what story it tells.

- Medals per Athlete
    → How efficiently did a country convert athletes into medals?
    
    TODO: final_df['Medals_Per_Athlete'] = ...
    Hint: Total medals / Athlete_Count


- Medals per Million Population
    → Small countries with medals are punching above their weight
    
    TODO: final_df['Medals_Per_Million_Pop'] = ...
    Hint: (Total medals / Population) * 1_000_000


- Medals per Billion USD GDP
    → Are richer countries just buying medals with investment?
    
    TODO: final_df['Medals_Per_Billion_GDP'] = ...
    Hint: (Total medals / GDP) * 1_000_000_000


- Gold Medal Percentage

    → What proportion of a country's medals are gold?

    → A country with 5 golds out of 5 medals is more dominant than one with 5 golds out of 50

    TODO: final_df['Gold_Percentage'] = ...
    Hint: (Gold / Total) * 100
    Watch out: avoid division by zero if Total is 0

In [40]:
# Load the final dataframe from dfs
final_df = dfs['Final_Analysis_Data']

# 1. Medals per Athlete
final_df['Medals_Per_Athlete'] = final_df['Total'] / final_df['Athlete_Count']

# 2. Medals per Million Population
# Population is in absolute numbers, so divide by 1,000,000 for 'per million'
final_df['Medals_Per_Million_Pop'] = (final_df['Total'] / final_df['Population']) * 1_000_000

# 3. Medals per Billion USD GDP
# GDP is typically in USD, so divide by 1,000,000,000 for 'per billion'
final_df['Medals_Per_Billion_GDP'] = (final_df['Total'] / final_df['GDP']) * 1_000_000_000

# 4. Gold Medal Percentage
# Handle division by zero for countries with 0 total medals (though we filtered for > 0 medals, it's good practice)
final_df['Gold_Percentage'] = (final_df['Gold'] / final_df['Total']) * 100
final_df['Gold_Percentage'] = final_df['Gold_Percentage'].fillna(0) # If Total is 0, percentage is 0

# Update the stored dataframe
dfs['Final_Analysis_Data'] = final_df

In [41]:
final_df = dfs['Final_Analysis_Data']

# Convert all column names to lowercase
final_df.columns = final_df.columns.str.lower()

print("Columns converted to lowercase.")
print(final_df.columns.tolist())

# Update the stored DataFrame
dfs['Final_Analysis_Data'] = final_df

Columns converted to lowercase.
['country', 'athlete_count', 'rank', 'gold', 'silver', 'bronze', 'total', 'rank by total', 'country_code', 'gdp', 'population', 'medals_per_athlete', 'medals_per_million_pop', 'medals_per_billion_gdp', 'gold_percentage']

In [42]:
print("Efficiency metrics calculated and added to final_df.")
print("Preview of final_df with new metrics:")
display(final_df.head())

Efficiency metrics calculated and added to final_df.
Preview of final_df with new metrics:

,country,athlete_count,rank,gold,silver,bronze,total,rank by total,country_code,gdp,population,medals_per_athlete,medals_per_million_pop,medals_per_billion_gdp,gold_percentage
0,Argentina,180,72,0,1,2,3,60,ARG,4.879026e+11,45312281.0,0.016667,0.066207,0.006149,0.000000
1,Armenia,16,69,0,2,2,4,47,ARM,1.387891e+10,2962300.0,0.250000,1.350302,0.288207,0.000000
2,Australia,470,6,17,7,22,46,6,AUS,1.559034e+12,25685412.0,0.097872,1.790900,0.029505,36.956522
3,Austria,72,53,1,1,5,7,33,AUT,4.792954e+11,8955797.0,0.097222,0.781617,0.014605,14.285714
4,Azerbaijan,41,67,0,3,4,7,33,AZE,5.482541e+10,10137750.0,0.170732,0.690489,0.127678,0.000000

#### STEP 2: Weighted Medal Score

Not all medals are equal — a gold is worth more than a bronze. Create a weighted score to reflect this.

Common weighting: Gold = 3, Silver = 2, Bronze = 1 (Some analysts use 5-3-1 or 4-2-1 — pick one and justify it)

TODO: final_df['Weighted_Medal_Score'] = ...
Hint: (Gold * 3) + (Silver * 2) + (Bronze * 1)

Then create weighted efficiency metrics:

TODO: final_df['Weighted_Score_Per_Athlete'] = ...

TODO: final_df['Weighted_Score_Per_Million_Pop'] = ...

In [44]:
final_df = dfs['Final_Analysis_Data']

# 1. Weighted Medal Score (Gold=3, Silver=2, Bronze=1)
final_df['weighted_medal_score'] = (final_df['gold'] * 3) + (final_df['silver'] * 2) + (final_df['bronze'] * 1)

# 2. Weighted Score Per Athlete
final_df['weighted_score_per_athlete'] = final_df['weighted_medal_score'] / final_df['athlete_count']

# 3. Weighted Score Per Million Population
final_df['weighted_score_per_million_pop'] = (final_df['weighted_medal_score'] / final_df['population']) * 1_000_000

# Update the stored dataframe
dfs['Final_Analysis_Data'] = final_df

print("Weighted medal scores and weighted efficiency metrics calculated.")
print("Preview of final_df with new weighted metrics:")
display(final_df.head())

Weighted medal scores and weighted efficiency metrics calculated.
Preview of final_df with new weighted metrics:

,country,athlete_count,rank,gold,silver,bronze,total,rank by total,country_code,gdp,population,medals_per_athlete,medals_per_million_pop,medals_per_billion_gdp,gold_percentage,weighted_medal_score,weighted_score_per_athlete,weighted_score_per_million_pop
0,Argentina,180,72,0,1,2,3,60,ARG,4.879026e+11,45312281.0,0.016667,0.066207,0.006149,0.000000,4,0.022222,0.088276
1,Armenia,16,69,0,2,2,4,47,ARM,1.387891e+10,2962300.0,0.250000,1.350302,0.288207,0.000000,6,0.375000,2.025453
2,Australia,470,6,17,7,22,46,6,AUS,1.559034e+12,25685412.0,0.097872,1.790900,0.029505,36.956522,87,0.185106,3.387137
3,Austria,72,53,1,1,5,7,33,AUT,4.792954e+11,8955797.0,0.097222,0.781617,0.014605,14.285714,10,0.138889,1.116595
4,Azerbaijan,41,67,0,3,4,7,33,AZE,5.482541e+10,10137750.0,0.170732,0.690489,0.127678,0.000000,10,0.243902,0.986412

#### STEP 3: Ranking Columns

Add rank columns so you can quickly see who's #1 in each metric

TODO: Create ranks for your key metrics
   - final_df['Rank_Medals_Per_Athlete'] = final_df['Medals_Per_Athlete'].rank(ascending=False).astype(int)

  - final_df['Rank_Medals_Per_Million_Pop'] = ...

   - final_df['Rank_Medals_Per_Billion_GDP' = ...

   - final_df['Rank_Weighted_Score'] = ...

In [46]:
final_df = dfs['Final_Analysis_Data']

# Rank Medals Per Athlete
final_df['rank_medals_per_athlete'] = final_df['medals_per_athlete'].rank(ascending=False).astype(int)

# Rank Medals Per Million Population
final_df['rank_medals_per_million_pop'] = final_df['medals_per_million_pop'].rank(ascending=False).astype(int)

# Rank Medals Per Billion GDP
final_df['rank_medals_per_billion_gdp'] = final_df['medals_per_billion_gdp'].rank(ascending=False).astype(int)

# Rank Weighted Medal Score
final_df['rank_weighted_medal_score'] = final_df['weighted_medal_score'].rank(ascending=False).astype(int)

# Update the stored dataframe
dfs['Final_Analysis_Data'] = final_df

print("Ranking columns added to final_df.")
print("Preview of final_df with new ranking metrics:")
display(final_df.head())

Ranking columns added to final_df.
Preview of final_df with new ranking metrics:

,country,athlete_count,rank,gold,silver,bronze,total,rank by total,country_code,gdp,...,medals_per_million_pop,medals_per_billion_gdp,gold_percentage,weighted_medal_score,weighted_score_per_athlete,weighted_score_per_million_pop,rank_medals_per_athlete,rank_medals_per_million_pop,rank_medals_per_billion_gdp,rank_weighted_medal_score
0,Argentina,180,72,0,1,2,3,60,ARG,4.879026e+11,...,0.066207,0.006149,0.000000,4,0.022222,0.088276,93,76,84,69
1,Armenia,16,69,0,2,2,4,47,ARM,1.387891e+10,...,1.350302,0.288207,0.000000,6,0.375000,2.025453,3,18,7,61
2,Australia,470,6,17,7,22,46,6,AUS,1.559034e+12,...,1.790900,0.029505,36.956522,87,0.185106,3.387137,44,14,43,6
3,Austria,72,53,1,1,5,7,33,AUT,4.792954e+11,...,0.781617,0.014605,14.285714,10,0.138889,1.116595,45,31,62,40
4,Azerbaijan,41,67,0,3,4,7,33,AZE,5.482541e+10,...,0.690489,0.127678,0.000000,10,0.243902,0.986412,17,34,14,40

#### STEP 4: Country Size Category

Categorize countries by population size — this will be useful as a filter in your dashboard

TODO: Create a categorical column based on population

Suggested bins:
  - 'Small'  → Population < 5 million
  - 'Medium' → 5 million to 50 million
  - 'Large'  → 50 million to 200 million
  - 'Giant'  → 200 million+

In [48]:
final_df = dfs['Final_Analysis_Data']

# Define the bins and labels for population categories
bins = [0, 5_000_000, 50_000_000, 200_000_000, float('inf')]
labels = ['Small', 'Medium', 'Large', 'Giant']

# Create the 'country_size_category' column
final_df['country_size_category'] = pd.cut(final_df['population'], bins=bins, labels=labels, right=False)

# Update the stored dataframe
dfs['Final_Analysis_Data'] = final_df

print("Country size categories calculated and added to final_df.")
print("Preview of final_df with new category:")
display(final_df.head())

Country size categories calculated and added to final_df.
Preview of final_df with new category:

,country,athlete_count,rank,gold,silver,bronze,total,rank by total,country_code,gdp,...,medals_per_billion_gdp,gold_percentage,weighted_medal_score,weighted_score_per_athlete,weighted_score_per_million_pop,rank_medals_per_athlete,rank_medals_per_million_pop,rank_medals_per_billion_gdp,rank_weighted_medal_score,country_size_category
0,Argentina,180,72,0,1,2,3,60,ARG,4.879026e+11,...,0.006149,0.000000,4,0.022222,0.088276,93,76,84,69,Medium
1,Armenia,16,69,0,2,2,4,47,ARM,1.387891e+10,...,0.288207,0.000000,6,0.375000,2.025453,3,18,7,61,Small
2,Australia,470,6,17,7,22,46,6,AUS,1.559034e+12,...,0.029505,36.956522,87,0.185106,3.387137,44,14,43,6,Medium
3,Austria,72,53,1,1,5,7,33,AUT,4.792954e+11,...,0.014605,14.285714,10,0.138889,1.116595,45,31,62,40,Medium
4,Azerbaijan,41,67,0,3,4,7,33,AZE,5.482541e+10,...,0.127678,0.000000,10,0.243902,0.986412,17,34,14,40,Medium

#### STEP 5: GDP Category

Similarly, categorize countries by GDP level

TODO: Create a categorical column based on GDP

Suggested bins:
  - 'Low'         → GDP < 50 billion dollars
  - 'Medium'      → 50B to 500 billion dollars
  - 'High'        → 500B to 2 trillion dollars
  - 'Very High'   → 2 trillion+ dollars

In [49]:
final_df = dfs['Final_Analysis_Data']

# Define the bins and labels for GDP categories
# GDP is in USD, so we need to convert billions/trillions to absolute numbers
bins = [0, 50_000_000_000, 500_000_000_000, 2_000_000_000_000, float('inf')]
labels = ['Low', 'Medium', 'High', 'Very High']

# Create the 'gdp_category' column
final_df['gdp_category'] = pd.cut(final_df['gdp'], bins=bins, labels=labels, right=False)

# Update the stored dataframe
dfs['Final_Analysis_Data'] = final_df

print("GDP categories calculated and added to final_df.")
print("Preview of final_df with new category:")
display(final_df.head())

GDP categories calculated and added to final_df.
Preview of final_df with new category:

,country,athlete_count,rank,gold,silver,bronze,total,rank by total,country_code,gdp,...,gold_percentage,weighted_medal_score,weighted_score_per_athlete,weighted_score_per_million_pop,rank_medals_per_athlete,rank_medals_per_million_pop,rank_medals_per_billion_gdp,rank_weighted_medal_score,country_size_category,gdp_category
0,Argentina,180,72,0,1,2,3,60,ARG,4.879026e+11,...,0.000000,4,0.022222,0.088276,93,76,84,69,Medium,Medium
1,Armenia,16,69,0,2,2,4,47,ARM,1.387891e+10,...,0.000000,6,0.375000,2.025453,3,18,7,61,Small,Low
2,Australia,470,6,17,7,22,46,6,AUS,1.559034e+12,...,36.956522,87,0.185106,3.387137,44,14,43,6,Medium,High
3,Austria,72,53,1,1,5,7,33,AUT,4.792954e+11,...,14.285714,10,0.138889,1.116595,45,31,62,40,Medium,Medium
4,Azerbaijan,41,67,0,3,4,7,33,AZE,5.482541e+10,...,0.000000,10,0.243902,0.986412,17,34,14,40,Medium,Medium

#### STEP 6: Validate your new features

TODO: Sanity check your engineered features

- Print the top 5 countries by each efficiency metric. Do the results make intuitive sense?

- Check for any inf or NaN values in new columns
 - Spot checks:
   - A small country like Bahamas or Bermuda should rank high in Medals_Per_Million_Pop

   - USA/China should rank low in per-capita metrics

   - A country like Jamaica (few athletes, multiple golds) should rank high in Medals_Per_Athlete

- Display the full feature set for a few countries

In [50]:
final_df = dfs['Final_Analysis_Data'].copy()

print("=== Validation of Engineered Features ===\n")

# 1. Print the top 5 countries by each efficiency metric.
print("Top 5 Countries by Medals Per Athlete:")
display(final_df.sort_values(by='medals_per_athlete', ascending=False).head()[['country', 'medals_per_athlete']])

print("\nTop 5 Countries by Medals Per Million Population:")
display(final_df.sort_values(by='medals_per_million_pop', ascending=False).head()[['country', 'medals_per_million_pop']])

print("\nTop 5 Countries by Medals Per Billion GDP:")
display(final_df.sort_values(by='medals_per_billion_gdp', ascending=False).head()[['country', 'medals_per_billion_gdp']])

print("\nTop 5 Countries by Gold Percentage:")
display(final_df.sort_values(by='gold_percentage', ascending=False).head()[['country', 'gold_percentage']])

print("\nTop 5 Countries by Weighted Medal Score:")
display(final_df.sort_values(by='weighted_medal_score', ascending=False).head()[['country', 'weighted_medal_score']])

print("\nTop 5 Countries by Weighted Score Per Athlete:")
display(final_df.sort_values(by='weighted_score_per_athlete', ascending=False).head()[['country', 'weighted_score_per_athlete']])

print("\nTop 5 Countries by Weighted Score Per Million Population:")
display(final_df.sort_values(by='weighted_score_per_million_pop', ascending=False).head()[['country', 'weighted_score_per_million_pop']])

# 2. Check for any inf or NaN values in new columns
print("\n=== NaN and Inf Check in New Columns ===")
new_cols = [
    'medals_per_athlete',
    'medals_per_million_pop',
    'medals_per_billion_gdp',
    'gold_percentage',
    'weighted_medal_score',
    'weighted_score_per_athlete',
    'weighted_score_per_million_pop'
]
for col in new_cols:
    nan_count = final_df[col].isnull().sum()
    inf_count = final_df[col].isin([float('inf'), -float('inf')]).sum()
    print(f"Column '{col}': NaN count = {nan_count}, Inf count = {inf_count}")

=== Validation of Engineered Features ===

Top 5 Countries by Medals Per Athlete:

       country  medals_per_athlete
74  San Marino            0.750000
9      Bermuda            0.500000
1      Armenia            0.250000
30     Georgia            0.228571
70         ROC            0.223270

Top 5 Countries by Medals Per Million Population:

        country  medals_per_million_pop
74   San Marino               87.586126
9       Bermuda               15.468383
35      Grenada                8.569862
5       Bahamas                5.045752
60  New Zealand                3.933446

Top 5 Countries by Medals Per Billion GDP:

       country  medals_per_billion_gdp
74  San Marino                1.616917
35     Grenada                0.890631
44     Jamaica                0.614017
27        Fiji                0.464573
30     Georgia                0.424333

Top 5 Countries by Gold Percentage:

        country  gold_percentage
5       Bahamas            100.0
9       Bermuda            100.0
68  Puerto Rico            100.0
49       Kosovo            100.0
57      Morocco            100.0

Top 5 Countries by Weighted Medal Score:

                       country  weighted_medal_score
90    United States of America                   232
64  People's Republic of China                   196
70                         ROC                   139
33               Great Britain                   130
45                       Japan                   126

Top 5 Countries by Weighted Score Per Athlete:

                       country  weighted_score_per_athlete
9                      Bermuda                    1.500000
74                  San Marino                    1.000000
49                      Kosovo                    0.600000
69                       Qatar                    0.500000
64  People's Republic of China                    0.488778

Top 5 Countries by Weighted Score Per Million Population:

        country  weighted_score_per_million_pop
74   San Marino                      116.781502
9       Bermuda                       46.405148
5       Bahamas                       15.137257
35      Grenada                        8.569862
60  New Zealand                        7.866892

=== NaN and Inf Check in New Columns ===
Column 'medals_per_athlete': NaN count = 0, Inf count = 0
Column 'medals_per_million_pop': NaN count = 0, Inf count = 0
Column 'medals_per_billion_gdp': NaN count = 0, Inf count = 0
Column 'gold_percentage': NaN count = 0, Inf count = 0
Column 'weighted_medal_score': NaN count = 0, Inf count = 0
Column 'weighted_score_per_athlete': NaN count = 0, Inf count = 0
Column 'weighted_score_per_million_pop': NaN count = 0, Inf count = 0

In [51]:
# 3. Spot checks:
print("\n=== Spot Checks ===")

# A small country like Bahamas or Bermuda should rank high in Medals_Per_Million_Pop
print("\nBahamas (BHS) and Bermuda (BMU) in Medals_Per_Million_Pop:")
display(final_df[final_df['country_code'].isin(['BHS', 'BMU'])][['country', 'medals_per_million_pop', 'rank_medals_per_million_pop']])

# USA/China should rank low in per-capita metrics
print("\nUSA (USA) and China (CHN) in Medals_Per_Million_Pop:")
display(final_df[final_df['country_code'].isin(['USA', 'CHN'])][['country', 'medals_per_million_pop', 'rank_medals_per_million_pop']])

# A country like Jamaica (few athletes, multiple golds) should rank high in Medals_Per_Athlete
print("\nJamaica (JAM) in Medals_Per_Athlete:")
display(final_df[final_df['country_code'] == 'JAM'][['country', 'athlete_count', 'gold', 'medals_per_athlete', 'rank_medals_per_athlete']])

# 4. Display the full feature set for a few countries
print("\n=== Full Feature Set for Selected Countries ===")
selected_countries = ['USA', 'CHN', 'JAM', 'BHS', 'SMR'] # United States, China, Jamaica, Bahamas, San Marino
display(final_df[final_df['country_code'].isin(selected_countries)].T)

=== Spot Checks ===

Bahamas (BHS) and Bermuda (BMU) in Medals_Per_Million_Pop:

   country  medals_per_million_pop  rank_medals_per_million_pop
5  Bahamas                5.045752                            4
9  Bermuda               15.468383                            2

USA (USA) and China (CHN) in Medals_Per_Million_Pop:

,country,medals_per_million_pop,rank_medals_per_million_pop
64,People's Republic of China,0.062307,77
90,United States of America,0.340259,60

Jamaica (JAM) in Medals_Per_Athlete:

    country  athlete_count  gold  medals_per_athlete  rank_medals_per_athlete
44  Jamaica             60     4                0.15                       21

=== Full Feature Set for Selected Countries ===

,5,44,64,74,90
country,Bahamas,Jamaica,People's Republic of China,San Marino,United States of America
athlete_count,16,60,401,4,615
rank,42,21,2,72,1
gold,2,4,38,0,39
silver,0,1,32,1,41
bronze,0,4,18,2,33
total,2,9,88,3,113
rank by total,66,26,2,60,1
country_code,BHS,JAM,CHN,SMR,USA
gdp,11368900000.0,14657586159.431623,17820459508852.183594,1855382833.116499,23594031000000.0
population,396373.0,2837682.0,1412360000.0,34252.0,332099760.0
medals_per_athlete,0.125,0.15,0.219451,0.75,0.18374
medals_per_million_pop,5.045752,3.171603,0.062307,87.586126,0.340259
medals_per_billion_gdp,0.175919,0.614017,0.004938,1.616917,0.004789
gold_percentage,100.0,44.444444,43.181818,0.0,34.513274
weighted_medal_score,6,18,196,4,232
weighted_score_per_athlete,0.375,0.3,0.488778,1.0,0.377236
weighted_score_per_million_pop,15.137257,6.343205,0.138775,116.781502,0.698585
rank_medals_per_athlete,31,21,7,1,13
rank_medals_per_million_pop,4,6,77,1,60
rank_medals_per_billion_gdp,10,3,86,1,87
rank_weighted_medal_score,61,27,2,69,1
country_size_category,Small,Small,Giant,Small,Giant
gdp_category,Low,Low,Very High,Low,Very High

#### STEP 7: Save the final analysis-ready dataset

TODO: Save the enriched dataframe

In [52]:
final_df = dfs['Final_Analysis_Data']
final_df.to_csv('olympics_final_analysis.csv', index=False)
print("Final analysis-ready dataset saved to olympics_final_analysis.csv! 🎉")

Final analysis-ready dataset saved to olympics_final_analysis.csv! 🎉